### ISSUE TITLE
Use 1 Table for Exchanges

### ISSUE THREAD

**Issue by bh2smith** [cowprotocol/dexag-benchmark#16]
https://github.com/cowprotocol/dexag-benchmark/blob/7ac7464bf0c2a30676989608745634130ac471a6/pg-database/sql/V001__create_exchanges.sql#L1-L22

All the tables in this file have an identical schema and could be put into one (with an extra enum field for exchange).

**Comment by josojo** [comment]
Done in this PR: https://github.com/cowprotocol/dexag-benchmark/pull/20
